---
groups:
  - name: Sausage store rules
    rules:
    - alert: InstanceDown
      expr: up{app="backend"} == 0
      for: 2m
      labels:
        severity: critical
        project: "sausage_store"
        component: "Backend"
      annotations:
        summary: "InstanceDown"
        description: "Backend is in down"

    - alert: Error 500
      expr: rate(http_server_requests_seconds_bucket{status="500"}[5m]) > 0
      for: 5m
      labels:
        severity: critical
        project: "sausage_store"
        component: "Backend"
      annotations:
        summary: "500 error occurs"
        description: "Rate of HTTP 500 errors has exceeded threshold"

    - alert: HighLatencyOrders
      expr: histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{method="POST", uri="/api/orders"}[5m])) by (le)) > 0.1
      for: 1m
      labels:
        severity: critical
        project: "sausage_store"
        component: "Backend"
      annotations:
        summary: "High Latency on /api/orders"
        description: "The 95th percentile latency for /api/orders has exceeded 100ms"

    - alert: PrometheusEndpointError
      expr: rate(http_server_requests_seconds_bucket{uri="/actuator/prometheus", status=~"5.."}[2m]) > 0
      for: 2m
      labels:
        severity: critical
        project: "sausage_store"
        component: "Backend"
      annotations:
        summary: "Error at /actuator/prometheus"
        description: "HTTP errors detected at /actuator/prometheus."
