cache:
  paths:
    - frontend/dist

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - build
  - release
  - deploy

build-frontend-code-job:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - echo "test"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/frontend"
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/sausage-frontend:$CI_COMMIT_SHA"
      --build-arg VERSION=$VERSION
      --cache=true



upload-frontend-release:
  stage: release
  needs:
    - build-frontend-code-job
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  cache: [ ]
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - crane tag $CI_REGISTRY_IMAGE/sausage-frontend:$CI_COMMIT_SHA latest 

deploy-frontend:
    stage: deploy
    needs:
        - upload-frontend-release
    image: alpine:3.18
    before_script:
        - apk add openssh-client bash
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo "${SSH_KNOWN_HOSTS}" >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
    script:
        - ssh -o StrictHostKeyChecking=no ${DEV_USER}@${DEV_HOST} "mkdir -p /home/student/frontend/"
        - scp -o StrictHostKeyChecking=no ${CI_PROJECT_DIR}/frontend/default.conf ${DEV_USER}@${DEV_HOST}:/home/student/frontend/default.conf 
        - ssh -o StrictHostKeyChecking=no ${DEV_USER}@${DEV_HOST} "export "VERSION=${VERSION}";
          export "CI_REGISTRY=${CI_REGISTRY}";
          export "CI_REGISTRY_USER=${CI_REGISTRY_USER}";
          export "CI_REGISTRY_PASSWORD=${CI_REGISTRY_PASSWORD}";
          export "CI_REGISTRY_IMAGE=${CI_REGISTRY_IMAGE}";
          setsid /bin/bash -s " < ./frontend/deploy.sh
    environment:
        name: review/$CI_COMMIT_REF_NAME
        url: http://${DEV_HOST}:80
    rules: 
      - when: manual

