version: "3.8"

services:
  backend:
    image: ${CI_REGISTRY_IMAGE}/sausage-backend:$CI_COMMIT_SHA 
    container_name: sausage-backend
    environment:
      SPRING_DATASOURCE_USERNAME: ${PSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${PSQL_PASS}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${PSQL_HOST}:${PSQL_PORT}/${PSQL_DBNAME}
    restart: always
    networks:
      - sausage-store

#  backend-report:
#    image: ${CI_REGISTRY_IMAGE}/sausage-backend-report:$CI_COMMIT_SHA 
#    container_name: sausage-store-backend-report
#    restart: always
#    environment:
#      PORT: 8081
#      DB: mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DBNAME}?tls=true
#    networks:
#      - sausage-store

  frontend:
    image: ${CI_REGISTRY_IMAGE}/sausage-frontend:$CI_COMMIT_SHA 
    container_name: sausage-frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - sausage-store

networks:
  sausage-store: