cache:
  paths:
    - ${CI_PROJECT_DIR}/.m2/repository

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
  JAVA_OPTS: -XX:MaxRAMPercentage=90

stages:
  - build
  - release
  - deploy

build-backend-code-job:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - echo "test"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/sausage-backend:$CI_COMMIT_SHA"
      --build-arg VERSION=$VERSION
      --cache=true  
  
#nclude:
#  - template: Security/SAST.gitlab-ci.yml  



upload-backend-release:
  stage: release
  needs:
    - build-backend-code-job
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  cache: [ ]
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - crane tag $CI_REGISTRY_IMAGE/sausage-backend:$CI_COMMIT_SHA latest 

deploy-backend:
  stage: deploy
  needs:
      - upload-backend-release
  image: alpine:3.18
  before_script:
      - apk add openssh-client bash
      - eval $(ssh-agent -s)
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - echo "${SSH_KNOWN_HOSTS}" >> ~/.ssh/known_hosts
      - chmod 644 ~/.ssh/known_hosts
  script: 
      - ssh -o StrictHostKeyChecking=no ${DEV_USER}@${DEV_HOST} "export "VERSION=${VERSION}";
        export "CI_REGISTRY=${CI_REGISTRY}";
        export "CI_REGISTRY_USER=${CI_REGISTRY_USER}";
        export "CI_REGISTRY_PASSWORD=${CI_REGISTRY_PASSWORD}";
        export "CI_REGISTRY_IMAGE=${CI_REGISTRY_IMAGE}";
        export "SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}";  
        export "SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}"; 
        export "SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}";
        export "SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}"; 
        setsid /bin/bash -s " < ./backend/deploy.sh
  environment:
      name: review/$CI_COMMIT_REF_NAME
      url: http://${DEV_HOST}:80
  rules: 
    - when: manual

    
