cache:
  paths:
    - ${CI_PROJECT_DIR}/.m2/repository

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
  JAVA_OPTS: -XX:MaxRAMPercentage=90


stages:
  - build
  - test
  - nonify
  - release

include:
  - template: Security/SAST.gitlab-ci.yml

build-backend-code-job:
  stage: build
  only:
    changes:
      - backend/**/*
  script:
    - cd backend
    - mvn package -Dversion.application=${VERSION} -Dmaven.repo.local=${MAVEN_REPO_PATH}  
  
  

spotbugs-sast:
  stage: test
  variables:
    COMPILE: "false"
    SAST_JAVA_VERSION: 11
    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
  cache:
    paths:
      - ${CI_PROJECT_DIR}/.m2/repository
  artifacts:
    reports:
       sast: gl-sast-report.json


sonarqube-backend-sast:
  stage: test
  script: 
    - >
      cd backend

      mvn verify sonar:sonar 
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_BACK}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN_BACK}
      -Dsonar.projectName=${SONAR_POJECT_NAME_BACK}
      -Dsonar.qualitygate.wait=true
  needs:
    - build-backend-code-job
  image: maven:3.8-openjdk-16
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache

telegram-notification-backend:
  stage: nonify
  only:
    changes:
      - backend/**
    variables:
      - $CI_COMMIT_MESSAGE =~ /all tests passed/
  script:
    - >
      curl -X POST -H 'Content-type: application/json' \
        --data "{\"chat_id\": \"-1002007326342\", \"text\": \"Никита Семеняк собрал backend. URL для скачивания артефактов: ($CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/download?job=build-backend-code-job)\"}" \
        https://api.telegram.org/bot$TELEGRAM_KEY/sendMessage
  needs:
    - build-backend-code-job
    - sonarqube-backend-sast

upload-backend-release:
  stage: release
  only:
    changes:
      - backend/**/*
  needs:
    - build-backend-code-job
  script:
    - cd backend
    - mvn deploy -DskipTests -Dmaven.repo.local=${MAVEN_REPO_PATH} -s settings.xml -Dversion.application=${VERSION} 
  