---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
      - "{{ .Values.frontend.ingressHost }}"
  rules:
  - host: "{{ .Values.frontend.ingressHost }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
