---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend
  revisionHistoryLimit: 12
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gitlab.praktikum-services.ru:5050/std-025-02/sausage-store/sausage-backend:${CI_COMMIT_SHA}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: backend-envs
          ports:
            - name: backend
              containerPort: 8080
          resources:
            limits:
              cpu: "1"  
              memory: "1Gi" 
            requests:
              cpu: "0.1"  
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 6
      imagePullSecrets:
        - name: docker-config-secret
