---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  labels:
    app: backend-report
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
        - name: backend-report
          image: gitlab.praktikum-services.ru:5050/std-025-02/sausage-store/sausage-backend-report:${CI_COMMIT_SHA}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: backend-report-envs
          ports:
            - name: backend-report
              containerPort: 8081
          resources:
            limits:
              cpu: "1"  
              memory: "1Gi" 
            requests:
              cpu: "0.1"  
              memory: "128Mi"
      imagePullSecrets:
        - name: docker-config-secret
