---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  labels:
    app: backend-report
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 20%
  selector:
    matchLabels:
      app: backend-report
  revisionHistoryLimit: 12
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:  
          - weight: 100  
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - backend-report
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: backend-report
          image: gitlab.praktikum-services.ru:5050/std-025-02/sausage-store/sausage-backend-report:${CI_COMMIT_SHA}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: backend-report-envs
          ports:
            - name: backend-report
              containerPort: 8081
          resources:
            limits:
              cpu: "0.2"  
              memory: "1Gi" 
            requests:
              cpu: "0.1"  
              memory: "512Mi"
      imagePullSecrets:
        - name: docker-config-secret
